:sparkles: IF-6091 add managed rdb api
nttcom/eclsdk pull request #102
Opened 2022-03-23 08:50 UTC by sugimo-s

2022-03-28 09:03 UTC, ysssasaki approved these changes

2022-03-28 09:16 UTC, NaoShark requested changes

2022-03-28 09:16 UTC, NaoShark commented on ecl/managed_rdb/v1/_proxy.py
> +            attrs["description"] = description
この実装だと、何か値が設定されている状態から空の状態に変更することができない気がします。
(e.g. name='aaa' から name='' に変更しようとしても if ブロックの中に入らない。description も同様。)

2022-03-29 05:50 UTC, sugimo-s commented on ecl/managed_rdb/v1/_proxy.py
> +            attrs["description"] = description
ご指摘いただいたとおり、現状の if文ですと空文字への変更ができません。
name, descriptionについて「if xxx:」を「if xxx is not None:」に修正します。
類似箇所が create_instance, change_passwordメソッドにもありますので、そちらも同様に修正します。

2022-03-29 07:08 UTC, NaoShark approved these changes

2022-03-29 07:18 UTC, merged