IF-7412 Append mLB Rules API of mVNA Day2
nttcom/eclsdk pull request #105
Opened 2022-04-19 07:48 UTC by ikegami-shota

Description of the Change
 - ecl/mvna/v1/_proxy.py
   - create_policyのコメントアウトを削除
   - create_staged_policy_configurationのコメントアウト削除
   - update_staged_policy_configurationのコメントアウト削除
   - tls_security_policyをtls_policyに変更
   - rule系のコメントアウトを削除
   - tls_policy系のコメントアウトを削除
 - ecl/mvna/v1/tls_policy.py
   - tls_security_policy.pyをtls_policy.pyに変更
   - TLSSecurityPolicyをTLSPolicyに変更
 - ecl/mvna/v1/policy.py
   - `sorry_page_url` `certificate_id` `tls_security_policy_id`のコメントアウト削除
   - tls_security_policyをtls_policyに変更

2022-04-20 02:08 UTC, NaoShark requested changes

2022-04-20 02:08 UTC, NaoShark commented on ecl/mvna/v1/_proxy.py
> +        if sorry_page_url:
```suggestion
        if sorry_page_url is not None:
```
この実装だと、空文字列に変更ができません。他の箇所にも同様に適用をお願いします。

2022-04-20 06:16 UTC, ikegami-shota commented
「is not None」を該当箇所に追加いたしました。おおまかな改修内容は以下になります。

 - ecl/mvna/v1/_proxy.py
   - create_policyの「name」「description」「tags」「sorry_page_url」「certificate_id」「tls_policy_id」のif に「is not None」を追加
   - create_staged_policy_configurationの「sorry_page_url」「certificate_id」「tls_policy_id」のif に「is not None」を追加
   - update_staged_policy_configurationの「sorry_page_url」「certificate_id」「tls_policy_id」のif に「is not None」を追加
   - create_ruleの「name」「description」「tags」のif に「is not None」を追加
   - update_ruleの「name」「description」「tags」のif に「is not None」を追加

2022-04-21 01:42 UTC, ikegami-shota commented
「is not None」を他の if XXX の箇所にも追加いたしました。
※　certificate系については https://github.com/nttcom/eclsdk/pull/106 で対応

2022-04-21 04:48 UTC, ikegami-shota commented
見落とし失礼いたしました。
Description of the Change
 - ecl/mvna/v1/_proxy.py
   - create_staged_target_group_configuration の「if members:」を「if members is not None:」に変更

2022-04-21 06:33 UTC, NaoShark approved these changes

2022-04-21 07:11 UTC, ysssasaki requested changes
1点だけコメントしました 🙇

2022-04-21 07:11 UTC, ysssasaki commented on ecl/mvna/v1/tls_policy.py
>  class TLSSecurityPolicy(resource2.Resource):
```suggestion
class TLSPolicy(resource2.Resource):
```

2022-04-21 07:28 UTC, ikegami-shota commented
ご指摘ありがとうございます。
Description of the Change
 - ecl/mvna/v1/_proxy.py
   - update_staged_policy_configuration のコメント「TLS Secutiry policy」を「TLS policy」に変更
- ecl/mvna/v1/tls_policy.py
   - クラス名を「TLSSecutiryPolicy」から「TLSPolicy」に変更

2022-04-21 07:36 UTC, ysssasaki approved these changes

2022-04-21 09:05 UTC, merged