:sparkles: IF-7410 Append mLB SSL Certificates API of mVNA Day2 (#106)
nttcom/eclsdk pull request #106
Opened 2022-04-20 03:06 UTC by ikegami-shota

Description of the Change
  - ecl/mvna/v1/_proxy.py
      - certificate系のコメントアウトを削除
      - create_certificateの「name」「description」「tags」のif に「is not None」を追加
      - update_certificateの「name」「description」「tags」のif に「is not None」を追加

2022-04-20 23:33 UTC, NaoShark requested changes

2022-04-20 23:33 UTC, NaoShark commented on ecl/mvna/v1/_proxy.py
>          body = {'type': certificate_type, 'file': certificate_file}
```suggestion
        body = {'type': certificate_type, 'content': certificate_content}
```
パラメータ名が変更されているので修正をお願いします。

2022-04-21 02:27 UTC, ikegami-shota commented
Description of the Change
  - ecl/mvna/v1/_proxy.py
      - 「certificate_file」を「certificate_content」に変更

2022-04-21 04:21 UTC, NaoShark requested changes

2022-04-21 04:21 UTC, NaoShark commented on ecl/mvna/v1/_proxy.py
> +        :param string certificate_content: File of Certificate
```suggestion
        :param string certificate_content: File content of Certificate
```

2022-04-21 04:33 UTC, ikegami-shota commented
見落とし失礼いたしました。
Description of the Change
  - ecl/mvna/v1/_proxy.py
      - 「File of Certificate」を「File content of Certificate」に変更

2022-04-21 06:27 UTC, NaoShark approved these changes

2022-04-21 07:15 UTC, ysssasaki approved these changes

2022-04-21 09:12 UTC, merged