Add MVNA target group resource
nttcom/eclsdk pull request #72
Opened 2021-04-02 10:57 UTC by NaoShark

Add MVNA Target Group Resource.

2021-04-05 03:34 UTC, ysssasaki requested changes

2021-04-05 03:34 UTC, ysssasaki commented on ecl/mvna/v1/_proxy.py
> +                                                        **body)
`members` パラメータはoptionalではないでしょうか

2021-04-05 03:34 UTC, ysssasaki commented on ecl/mvna/v1/_proxy.py
> +                                                        **body)
`members` パラメータはoptionalではないでしょうか

2021-04-05 06:05 UTC, ysssasaki requested changes

2021-04-05 06:05 UTC, ysssasaki commented on ecl/mvna/v1/_proxy.py
> +            self, target_group_id, members, default_port=None):
```suggestion
            self, target_group_id, members=None, default_port=None):
```

2021-04-05 06:05 UTC, ysssasaki commented on ecl/mvna/v1/_proxy.py
> +            self, target_group_id, members, default_port=None):
```suggestion
            self, target_group_id, members=None, default_port=None):
```

2021-04-05 06:10 UTC, ysssasaki approved these changes

2021-04-05 10:31 UTC, shimisho requested changes

2021-04-05 10:31 UTC, shimisho commented on ecl/mvna/v1/_proxy.py
> +        :param string name: Name ofTarget Group
```suggestion
        :param string name: Name of Target Group
```

2021-04-05 10:31 UTC, shimisho commented on ecl/mvna/v1/_proxy.py
> +                    attempting to delete a nonexistent resource2.
resource2 は resource のtypoでしょうか。

2021-04-05 23:07 UTC, NaoShark commented on ecl/mvna/v1/_proxy.py
> +                    attempting to delete a nonexistent resource2.
https://github.com/nttcom/eclsdk/blob/master/ecl/proxy2.py#L117-#L121
と同じコメントを使用しており、文脈的にもおかしくない様に見えます。

2021-04-06 01:53 UTC, shimisho approved these changes

2021-04-06 01:57 UTC, merged