Support additional mvna parameter
nttcom/eclsdk pull request #76
Opened 2021-04-14 07:56 UTC by NaoShark

- List 処理において Query Parameter をサポート
- Show 系の処理において `changes` Query Parameter をサポート
- Action, Delete Load Balancer において `X-MVNA-Request-Id` をサポート

2021-04-14 09:04 UTC, ysssasaki requested changes

2021-04-14 09:04 UTC, ysssasaki commented on ecl/mvna/v1/_proxy.py
>          """Delete Managed Load Balancer.
ignore_missingが消えてしまっているので、残したほうが良いかと思いました。

2021-04-15 01:09 UTC, ysssasaki approved these changes

2021-04-15 09:10 UTC, shimisho approved these changes

2021-04-16 00:36 UTC, merged