✨ IF-5804 Add Operation resource to mVNA LB
nttcom/eclsdk pull request #79
Opened 2021-04-19 09:04 UTC by ManabuMiwa

2021-05-11 22:57 UTC, NaoShark requested changes
コメントしました。

2021-05-11 22:57 UTC, NaoShark commented on ecl/mvna/v1/_proxy.py
> +        return list(self._list(_target_group.TargetGroup, paginated=False, **params))
https://www.python.org/dev/peps/pep-0008/#maximum-line-length

2021-05-11 22:57 UTC, NaoShark commented on ecl/mvna/v1/_proxy.py
> +        return list(self._list(_operation.Operation, paginated=False, **params))
https://www.python.org/dev/peps/pep-0008/#maximum-line-length

2021-05-11 22:57 UTC, NaoShark commented on ecl/mvna/v1/base.py
> +        return result
```suggestion
    def _transpose(self, query):
        result = {}
        for key, value in self._mapping.items():
            if key in query:
                if type(query[key]) is bool:
                    result[value] = str(query[key]).lower()
                else:
                    result[value] = query[key]
        return result
```

2021-05-11 22:59 UTC, NaoShark requested changes

2021-05-11 22:59 UTC, NaoShark commented on ecl/mvna/v1/base.py
> +
2 行あけてください。(https://www.python.org/dev/peps/pep-0008/#blank-lines)

2021-05-12 00:59 UTC, NaoShark commented on ecl/mvna/v1/base.py
> +        return result
この様にしたらループの回数を少なくすることができないでしょうか？

2021-05-12 02:01 UTC, ManabuMiwa commented on ecl/mvna/v1/base.py
> +        return result
ありがとうございます、よいと思います。🥴
ただ上記実装では文字列で "True" とか "False" とか渡されてきた場合に漏れてしまうと思ったので、コードは少し修正しました。

2021-05-12 02:25 UTC, NaoShark approved these changes
LGTM.

2021-05-12 03:08 UTC, ysssasaki approved these changes
LGTM 🍊

2021-05-12 04:17 UTC, merged